export class DocumentDesigner {
  cashProProductId: string;
  cashProProductName: string;
  moduleName: string;
  docTemplateTypeId: string;
  docTemplateTypeName: string;
  documentDesignName: string;
  formatLevel: string;
  displayDataFrom: string;
  documentDesignType: string | string[];
  fileType: string;
  fileTypeName: string;
  emailSubject: string;
  emailbody: string;
  emailbody1: string;
  emailbody2: string;
  emailbody3: string;
  emailbody4: string;
  documentHeader: string;
  documentHeader1: string;
  documentHeader2: string;
  documentHeader3: string;
  documentHeader4: string;
  pageHeader: string;
  pageHeader1: string;
  pageHeader2: string;
  pageHeader3: string;
  pageHeader4: string;
  text: string;
  text1: string;
  text2: string;
  text3: string;
  text4: string;
  pageFooter: string;
  pageFooter1: string;
  pageFooter2: string;
  pageFooter3: string;
  pageFooter4: string;
  documentFooter: string;
  documentFooter1: string;
  documentFooter2: string;
  documentFooter3: string;
  documentFooter4: string;
  sms: string;
  online: string;
  online1: string;
  online2: string;
  online3: string;
  online4: string;
  pushNotification: string;
  waterMarkText: string;
  waterMarkDirection: string;
  waterMarkDirectionName: string;
  effectiveFrom: string;
  effectiveTill: string;
  mappedCount: number;

  constructor() {
    this.cashProProductId = '';
    this.cashProProductName = '';
    this.moduleName = '';
    this.docTemplateTypeId = '';
    this.docTemplateTypeName = '';
    this.documentDesignName = '';
    this.formatLevel = '';
    this.displayDataFrom = '';
    this.documentDesignType = '';
    this.fileType = '';
    this.fileTypeName = '';
    this.emailSubject = '';
    this.emailbody = '';
    this.emailbody1 = '';
    this.emailbody2 = '';
    this.emailbody3 = '';
    this.emailbody4 = '';
    this.documentHeader = '';
    this.documentHeader1 = '';
    this.documentHeader2 = '';
    this.documentHeader3 = '';
    this.documentHeader4 = '';
    this.pageHeader = '';
    this.pageHeader1 = '';
    this.pageHeader2 = '';
    this.pageHeader3 = '';
    this.pageHeader4 = '';
    this.text = '';
    this.text1 = '';
    this.text2 = '';
    this.text3 = '';
    this.text4 = '';
    this.pageFooter = '';
    this.pageFooter1 = '';
    this.pageFooter2 = '';
    this.pageFooter3 = '';
    this.pageFooter4 = '';
    this.documentFooter = '';
    this.documentFooter1 = '';
    this.documentFooter2 = '';
    this.documentFooter3 = '';
    this.documentFooter4 = '';
    this.sms = '';
    this.online = '';
    this.online1 = '';
    this.online2 = '';
    this.online3 = '';
    this.online4 = '';
    this.pushNotification = '';
    this.waterMarkText = '';
    this.waterMarkDirection = '';
    this.waterMarkDirectionName = '';
    this.effectiveFrom = '';
    this.effectiveTill = '';
    this.mappedCount = 0;
  }
}
